name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER || 'ubuntu' }} 
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |

          sudo rm -rf /var/www/html/* 

          sudo systemctl stop fullstack.service 
         
          cd /home/ubuntu/FS-cicd
          git pull origin main 
          cd ./backend
          npm install --production
          cd /home/ubuntu/FS-cicd/frontend
          npm install --production
          npm run build
          sudo cp -r /home/ubuntu/FS-cicd/frontend/build/* /var/www/html/ 
          sudo systemctl restart fullstack.service